### PR TITLE
Commit

### PR DESCRIPTION
**Pull request by thatdevwolfy**
Added debug information, pnotify for notifications and other things.

### CODE REVIEW

**Comment by thatdevwolfy** [comment]
image
image
image


as examples for the pnotify additions.

**Comment by thatdevwolfy** [comment]
> image image image
> 
> as examples for the pnotify additions.

The welcome to skyport is welcome to (Panel name)

**Comment by atqr1** [comment]
Could you change the colours for the alerts to match the Skyport UI? It should be #171717 with text-neutral-xxx for the text
Also add rounded-lg

**Comment by thatdevwolfy** [comment]
> Could you change the colours for the alerts to match the Skyport UI? It should be #171717 with text-neutral-xxx for the text Also add rounded-lg

Completed. ready to merge.

**Comment by achul123** [comment]
use https://heroicons.com/ instand font awesome

**Comment by thatdevwolfy** [comment]
> could you fix the conflicts?

Alright. working on them now.

**Comment by ismamilahi** [comment]
yaa and i also create new pull check that - https://github.com/skyportlabs/panel/pull/58

**Pull request merged**
