### PR TITLE
Added Purge Servers

### PR DESCRIPTION
**Pull request by ma4z**

### CODE REVIEW

**Comment by privt00** [comment]
@ma4z send me a screenshot of how its looking pleas

**Comment by ma4z** [comment]
alright wait

**Comment by ma4z** [comment]
image
@privt00

**Comment by privt00** [comment]
@ma4z why the purge button on the instance it self?

**Comment by ma4z** [comment]
nvm this wont work hehe 
it will just saying Error while purging instances

**Pull request closed without merging**
