### PR TITLE
Version checker on startup. 

### PR DESCRIPTION
**Pull request by thatdevwolfy**
Added version checker on startup.

### CODE REVIEW

**Comment by thatdevwolfy** [comment]
fixing conflics right now.

**Review by mtq4 — COMMENTED** [review]
5 star

**Comment by privt00** [comment]
@wesamdev can u test this out?

**Comment by wesamdev** [comment]
> @wesamdev can u test this out?

ok

**Comment by wesamdev** [comment]
works

**Comment by wesamdev** [comment]
Merge this but this only works on beta versions

**Pull request closed without merging**
