### PR TITLE
Discord Messages

### PR DESCRIPTION
**Pull request by mtq4**
Added Whenever a Person send a Public Skyport URL to anyone the message aslo shown 
Skyport Panel!
Skyport Panel | Best Alternate to Pterodactyl

### CODE REVIEW

**Comment by mtq4** [comment]
@privt00

**Comment by privt00** [comment]
@mtq4 make it costumizable in settings

**Comment by mtq4** [comment]
ok mate

**Comment by mtq4** [comment]
if possible i do it

**Comment by privt00** [comment]
ofc it is

**Pull request closed without merging**
