### PR TITLE
Update InstanceDB.js

### PR DESCRIPTION
**Pull request by fhostings**
Resolved error when creating a MySQL database that gave an error that the 'host' was undefined.

### CODE REVIEW

**Comment by privt00** [comment]
if you define the host it should work

**Comment by privt00** [comment]
but why removing the host

**Comment by fhostings** [comment]
It was giving an error, it sends directly from the daemon.

**Comment by fhostings** [comment]
See https://github.com/skyportlabs/skyportd/pull/9

**Comment by fhostings** [comment]
The MySQL host should not come from the panel but from the daemon.

**Pull request merged**
