### PR TITLE
Update For 0.1.0-beta7

### PR DESCRIPTION
**Pull request by ismamilahi**
Smtp Features

### CODE REVIEW

**Comment by privt00** [comment]
Hey there are still some conflicts

**Comment by ismamilahi** [comment]
which files but github not showing me

**Comment by privt00** [comment]
ig its right i just looked into the first commits but its just his old commit from befor. everything should be ok @ismamilahi can u check if everything is working corectly by downloading his repo and tryng it out?

**Comment by privt00** [comment]
At home i take a look

**Pull request merged**
